services:

  profile-service:
    build: .
    container_name: profile-service
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SPRING_DATA_MONGODB_URI=${MONGO_URI}
    networks:
      - backend
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  backend:
    driver: bridge
