spring.application.name=profile-service
spring.mongodb.uri=mongodb+srv://andrescardozom_db_user:3g1AhFD891Hr5ueI@cluster0.rhtaodt.mongodb.net/profileservice?appName=Cluster0
spring.mongodb.database=profileservice