spring.application.name=profile-service
spring.data.mongodb.uri=${MONGO_URI}
spring.data.mongodb.database=${MONGO_DB:profileservice}

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

app.startup.fail-fast=${APP_STARTUP_FAIL_FAST:true}

spring.security.user.name=admin
spring.security.user.password=admin123
